{% set name = "helpdev" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/helpdev-{{ version }}.tar.gz
  sha256: bb62a79acbac141dadf42cadeb92bb7450dd18b9824a62043b6a0b149190db3d

build:
  noarch: python
  number: 1
  entry_points:
    - helpdev=helpdev.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    # Only required for python<3.8 but always include for noarch: python
    - importlib-metadata
    - python >={{ python_min }}

test:
  imports:
    - helpdev
  commands:
    - pip check
    - helpdev --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/dpizetta/helpdev
  summary: HelpDev - Extracts information about the Python environment easily.
  license: CC0-1.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - chrisburr
